
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS ID LPAREN MINUS NUM PLUS RPAREN TIMESS : ID EQUALS ES : EE : E PLUS T\n| E MINUS TE : TT : T TIMES F\n| T DIVIDE FT : FF : LPAREN E RPARENF : IDF : NUM'
    
_lr_action_items = {'ID':([0,6,8,9,10,11,12,],[2,14,14,14,14,14,14,]),'LPAREN':([0,6,8,9,10,11,12,],[6,6,6,6,6,6,6,]),'NUM':([0,6,8,9,10,11,12,],[7,7,7,7,7,7,7,]),'$end':([1,2,3,4,5,7,14,15,16,17,18,19,20,],[0,-10,-2,-5,-8,-11,-10,-1,-3,-4,-6,-7,-9,]),'EQUALS':([2,],[8,]),'TIMES':([2,4,5,7,14,16,17,18,19,20,],[-10,11,-8,-11,-10,11,11,-6,-7,-9,]),'DIVIDE':([2,4,5,7,14,16,17,18,19,20,],[-10,12,-8,-11,-10,12,12,-6,-7,-9,]),'PLUS':([2,3,4,5,7,13,14,15,16,17,18,19,20,],[-10,9,-5,-8,-11,9,-10,9,-3,-4,-6,-7,-9,]),'MINUS':([2,3,4,5,7,13,14,15,16,17,18,19,20,],[-10,10,-5,-8,-11,10,-10,10,-3,-4,-6,-7,-9,]),'RPAREN':([4,5,7,13,14,16,17,18,19,20,],[-5,-8,-11,20,-10,-3,-4,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,6,8,],[3,13,15,]),'T':([0,6,8,9,10,],[4,4,4,16,17,]),'F':([0,6,8,9,10,11,12,],[5,5,5,5,5,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> ID EQUALS E','S',3,'p_S_asignacion','Taller.py',48),
  ('S -> E','S',1,'p_S_expresion','Taller.py',52),
  ('E -> E PLUS T','E',3,'p_E_expr','Taller.py',56),
  ('E -> E MINUS T','E',3,'p_E_expr','Taller.py',57),
  ('E -> T','E',1,'p_E_to_T','Taller.py',61),
  ('T -> T TIMES F','T',3,'p_T_expr','Taller.py',65),
  ('T -> T DIVIDE F','T',3,'p_T_expr','Taller.py',66),
  ('T -> F','T',1,'p_T_to_F','Taller.py',70),
  ('F -> LPAREN E RPAREN','F',3,'p_F_group','Taller.py',74),
  ('F -> ID','F',1,'p_F_id','Taller.py',78),
  ('F -> NUM','F',1,'p_F_num','Taller.py',82),
]
